name: Maven Central Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: Tag Version (add prefix v)
        required: true

jobs:
  build-publish:
    name: Build & maven publish
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout for ${{ github.event.inputs.version }}
        uses: actions/checkout@v4.1.1

        # DO NOT USE CONTAINER, else gpg sign step will fail
      - name: Set up Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          # Set this in pom.xml or in parent/pom.xml
          server-id: ossrh-ajaxer-org
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Building artifact for ${{ github.event.inputs.version }}
        run: mvn clean deploy -P release -Dmaven.test.skip=true --no-transfer-progress -e
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

