name: Read Maven Version

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  read-version:
    runs-on: ubuntu-latest
    container: ershakiransari/jdk:8-mvn3

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Extract version from pom.xml
        id: get-version
        run: |
          VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
          echo "Project version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Use extracted version
        run: echo "The Maven project version is ${{ steps.get-version.outputs.version }}"
